function H = constHess(p1,p2,q1x,q2x,q1y,q2y)
%GENERATECONSTHESSIAN
%    H = GENERATECONSTHESSIAN(P1,P2,Q1X,Q2X,Q1Y,Q2Y)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    03-Jul-2017 20:34:58

t2 = q1x.*2.0;
t3 = q2x.*2.0;
t4 = t2-t3;
t5 = p1.*p2.*2.0;
t6 = q1y.*2.0;
t7 = q2y.*2.0;
t8 = t6-t7;
t9 = q1x-q2x;
t10 = q1y-q2y;
t11 = p2.*t4;
t12 = p2.*t8;
t13 = p1.*t4;
t14 = p1.*t8;
t15 = t9.^2;
t16 = t10.^2;
t17 = -t15-t16;

H =     [p1.*p2.*-2.0,zeros(size(p1)),zeros(size(p1)),-p2.*t4,t5,zeros(size(p1)),zeros(size(p1)),...
    -t13,zeros(size(p1)),-t5,zeros(size(p1)),-p2.*t8,zeros(size(p1)),t5,zeros(size(p1)),-t14,...
    zeros(size(p1)),zeros(size(p1)),zeros(size(p1)),ones(size(p1)),zeros(size(p1)),zeros(size(p1)),...
    zeros(size(p1)),-ones(size(p1)),-p2.*t4,-p2.*t8,ones(size(p1)),zeros(size(p1)),t11,t12,-ones(size(p1)),...
    t17,t5,zeros(size(p1)),zeros(size(p1)),t11,-t5,zeros(size(p1)),zeros(size(p1)),t13,zeros(size(p1)),...
    t5,zeros(size(p1)),t12,zeros(size(p1)),-t5,zeros(size(p1)),t14,zeros(size(p1)),zeros(size(p1)),zeros(size(p1)),...
    -ones(size(p1)),zeros(size(p1)),zeros(size(p1)),zeros(size(p1)),ones(size(p1)),-p1.*t4,-p1.*t8,-ones(size(p1)),...
    t17,t13,t14,ones(size(p1)),zeros(size(p1))];
