function Hx = rhoXHess(p1,p2,q1x,q2x)
%RHOXHESS
%    HX = RHOXHESS(P1,P2,Q1X,Q2X)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Jul-2017 11:22:44

t2 = p1-p2;
t3 = 1.0./t2.^2;
t4 = p1.*t3;
t5 = 1.0./t2;
t6 = 1.0./t2.^3;
t7 = p1.*q1x;
t11 = p2.*q2x;
t8 = t7-t11;
t9 = t6.*t8.*2.0;
t10 = p2.*t3;
t12 = q1x.*t3;
t13 = q2x.*t3;
t14 = -t9+t12+t13;
t15 = -t5-t10;
z = zeros(size(p1));
Hx = [z,z,z,-t4+t5,z,z,z,t4,...
      z,z,z,z,z,z,z,z,...
      z,z,z,z,z,z,z,z,...
      t5-p1.*t3,z,z,t9-q1x.*t3.*2.0,t10,z,z,t14,...
      z,z,z,t10,z,z,z,t15,...
      z,z,z,z,z,z,z,z,...
      z,z,z,z,z,z,z,z,...
      t4,z,z,t14,t15,z,z,t9-q2x.*t3.*2.0];
