function Hx = rhoXHessTheta
%RHOXHESSTHETA
%    HX = RHOXHESSTHETA

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    06-Jul-2017 12:09:34

Hx = reshape([0.0,0.0,0.0,0.0],[2, 2]);
