function Dx = rhoXGrad(p1,p2,q1x,q2x)
%RHOXGRAD
%    DX = RHOXGRAD(P1,P2,Q1X,Q2X)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Jul-2017 12:00:25

t2 = p1-p2;
t3 = 1.0./t2;
t4 = 1.0./t2.^2;
t5 = p1.*q1x;
t6 = t5-p2.*q2x;
z = zeros(size(p1));
Dx = [p1.*t3,z,z,q1x.*t3-t4.*t6,-p2.*t3,z,z,-q2x.*t3+t4.*t6];
