function Hy = rhoYHess(p1,p2,q1y,q2y)
%RHOYHESS
%    HY = RHOYHESS(P1,P2,Q1Y,Q2Y)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Jul-2017 11:22:45

t2 = p1-p2;
t3 = 1.0./t2.^2;
t4 = p1.*t3;
t5 = 1.0./t2;
t6 = 1.0./t2.^3;
t7 = p1.*q1y;
t11 = p2.*q2y;
t8 = t7-t11;
t9 = t6.*t8.*2.0;
t10 = p2.*t3;
t12 = q1y.*t3;
t13 = q2y.*t3;
t14 = -t9+t12+t13;
t15 = -t5-t10;
z = zeros(size(p1));
Hy = [z,z,z,z,z,z,z,z,...
      z,z,z,-t4+t5,z,z,z,t4,...
      z,z,z,z,z,z,z,z,...
      z,t5-p1.*t3,z,t9-q1y.*t3.*2.0,z,t10,z,t14,...
      z,z,z,z,z,z,z,z,...
      z,z,z,t10,z,z,z,t15,...
      z,z,z,z,z,z,z,z,...
      z,t4,z,t14,z,t15,z,t9-q2y.*t3.*2.0];
