function Dx = rXGrad(p1,p2,q1x,q2x,rx)
%RXGRAD
%    DX = RXGRAD(P1,P2,Q1X,Q2X,RX)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    10-Jul-2017 12:37:18

Dx = [p1,zeros(size(p1)),q1x-rx,-p2,zeros(size(p1)),-q2x+rx];
