function Hx = rXHess
%RXHESS
%    HX = RXHESS

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    10-Jul-2017 12:37:19

Hx = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0],[6, 6]);
