function Dy = rYGrad(p1,p2,q1y,q2y,ry)
%RYGRAD
%    DY = RYGRAD(P1,P2,Q1Y,Q2Y,RY)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    10-Jul-2017 12:37:18

Dy = [zeros(size(p1)),p1,q1y-ry,zeros(size(p1)),-p2,-q2y+ry];
