function Dx = sXGrad(p1,p2,q1x,q2x,q1y,q2y,rx,ry)
%SXGRAD
%    DX = SXGRAD(P1,P2,Q1X,Q2X,Q1Y,Q2Y,RX,RY)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Jul-2017 12:42:53

t3 = p1-p2;
t5 = p1.*q1x;
t6 = p2.*q2x;
t7 = rx.*t3;
t2 = -t5+t6+t7;
t9 = p1.*q1y;
t10 = p2.*q2y;
t11 = ry.*t3;
t4 = -t9+t10+t11;
t8 = t2.^2;
t12 = t4.^2;
t13 = t8+t12;
t14 = 1.0./t13.^(3.0./2.0);
t15 = 1.0./sqrt(t13);
t16 = q1x-rx;
t17 = q2x-rx;
Dx = [p1.*t15-p1.*t8.*t14,-p1.*t2.*t4.*t14,...
      t15.*t16-t2.*t14.*(t2.*t16.*2.0+t4.*(q1y-ry).*2.0).*(1.0./2.0),...
      -p2.*t15+p2.*t8.*t14,p2.*t2.*t4.*t14,...
      -t15.*t17+t2.*t14.*(t2.*t17.*2.0+t4.*(q2y-ry).*2.0).*(1.0./2.0)];
